version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_NAME: taskdb
      DB_USER: devops_user
      DB_PASS: strongpassword
    depends_on:
      - db

volumes:
  postgres_data:
